### ISSUE TITLE
How to read the data from the sheet? 

### ISSUE THREAD

**Issue by vooolll** [folone/poi.scala#42]
I read your documentation about scala poi, but I can't find out how to actually read the data from the sheet. For instance I want to read all from the document and print it out. May be I just don't understand the dsl. Could you help me?

**Comment by brianwawok** [comment]
@vooolll  look at the Workbook.apply methods, it reads from inputstream or file or such

https://github.com/folone/poi.scala/blob/master/src/main/scala/info.folone/scala.poi/Workbook.scala#L136

**Comment by nlw0** [comment]
Can we set the order of the sheets in the workbook? I was trying to read an save a file, but the order of the sheets is getting messed up.

**Comment by rintcius** [comment]
@nlw0 I don't think this is possible at the moment. They are sorted alphabetically.

**Comment by rintcius** [comment]
For future reference, see https://github.com/folone/poi.scala/issues/52 for how to order sheets.

Assuming issue has been addressed. Feel free to reopen if incorrect.
