### ISSUE TITLE
Cannot find published 0.15 artifact

### ISSUE THREAD

**Issue by guersam** [folone/poi.scala#45]
I cannot find 0.15 release on [Sonatype OSS](https://oss.sonatype.org/#nexus-search;quick~poi-scala_2.11) or [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22poi-scala_2.11%22). [maven-repository](https://maven-repository.com/artifact/info.folone/poi-scala_2.11/0.15) says it's at Sonatype OSS's staging repo, but adding it to the resolvers doesn't help.

**Comment by folone** [comment]
Right, I believe I published an unsigned jar, so nexus failed to propagate it to maven central. Apologies! I've just published the signed version. It should be automatically pushed to maven central within a few hours, but is already accessible from sonatype nexus. Let me know if that fixes the problem for you.

**Comment by guersam** [comment]
Yes it exists now, thanks :)

**Comment by rintcius** [comment]
Sorry for reopening - I'm not sure what happened, but it looks like 0.15 has vanished (given that @guersam found it earlier).  
It doesn't seem to be available in Maven central http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22poi-scala_2.10%22 or Sonatype https://oss.sonatype.org/content/groups/staging/info/folone/poi-scala_2.10/

**Comment by folone** [comment]
This is super weird. I've just published again. Seems to work fine. Will come back in a week, and see if that worked.

**Comment by rintcius** [comment]
@folone very weird indeed - thanks for publishing it again. 

@guersam did you see it in Sonatype or in Maven central?

**Comment by rintcius** [comment]
FYI it's there in Maven central now:

![screen shot 2015-06-23 at 12 46 36 pm](https://cloud.githubusercontent.com/assets/888781/8304435/1b63768c-19a6-11e5-90a2-898a200555bc.png)

**Comment by folone** [comment]
Let's hope it stays there :)

**Comment by rintcius** [comment]
:) Indeed, fingers crossed!

**Comment by folone** [comment]
Just checked again, the artifact is still there. Closing this issue.

**Comment by rintcius** [comment]
:+1:
