### ISSUE TITLE
But how to order sheets by name or by adding order?

### ISSUE THREAD

**Issue by zhongwm** [folone/poi.scala#52]
But how to order sheets by name or by adding order?

**Comment by rintcius** [comment]
Here's how you should be able to order by name:
```
val sheets: List[Sheet] = ...

Workbook(TreeSet(sheets : _*)(Ordering.fromLessThan[Sheet](_.name < _.name)))
```

**Comment by rintcius** [comment]
Assuming comment above addresses issue. Feel free to reopen if incorrect.
