### ISSUE TITLE
Please publish for scalaz 7.2

### ISSUE THREAD

**Issue by rhyskeepence** [folone/poi.scala#56]
Master appears to be up to date, but the latest published version is compiled against 7.1. Thanks.

**Comment by hermanbanken** [comment]
Otherwise you'll get weird bugs... certainly if you've never used scalaz directly.

For now:
````
resolvers += "jitpack" at "https://jitpack.io"
libraryDependencies += "com.github.folone" % "poi.scala" % "98cbef63aa"
````

**Comment by folone** [comment]
Oh wow, sorry for ignoring this! I've just published version 0.16 from master. Let me know if it works for you!

**Comment by folone** [comment]
Forgot that publishing needs to be signed. The artifact should appear on maven central in a few hours.

**Comment by folone** [comment]
Alright, the version is up: http://search.maven.org/#artifactdetails%7Cinfo.folone%7Cpoi-scala_2.11%7C0.16%7Cjar. I'll close this, feel free to reopen if there are still problems.
