### ISSUE TITLE
publish for Scala 2.13

### ISSUE THREAD

**Issue by xuwei-k** [folone/poi.scala#71]

**Comment by xuwei-k** [comment]
@folone 🙏

**Comment by folone** [comment]
Hi @xuwei-k! So sorry for the slow turnaround on this – thanks for your patience! Just released and published version 0.19 to sonatype (this should include 2.13). It should propagate to maven central within a few hours.

I'm wondering if I can somehow give you permissions to release/publish this project? I'd be happy to transfer full ownership to you, so you don't end up blocked on me again.
